### ISSUE TITLE
Add Quick Sort in JavaScript

### ISSUE THREAD

**Issue by Gurmeet22** [TheRenegadeCoder/sample-programs#1649] opened 2019-10-16 10:15 UTC

**Comment by SimplyComplexable** [comment] 2019-10-18 01:00
@Gurmeet22 This doesn't have the hacktoberfest label, but I'm happy to help with this one if needed.

**Comment by SimplyComplexable** [comment] 2019-10-18 01:01
Actually just realized this is a duplicate of #1388.

**Comment by jrg94** [comment] 2019-10-18 01:30
Good point! This actually has two open pull requests, but the one reference in #1388 is pretty far off the mark.

**Closed** 2019-10-18 01:33 UTC
Labels: duplicate, enhancement
